.TH sshactivate "26" "February 2017" "sshactivate" "System Administration Commands (8)"
.SH NAME
sshactivate - starts and enable sshd
.SH SYNOPSIS
.B sshactivate
.SH DESCRIPTION
`sshactivate', generates sshd system keys, starts and enable the ssh dæmon and asks for user
password, to allow remote access to the (live-)system.
.SH "SEE ALSO"
.BR sshd
.SH AUTHOR
This manual has been written by Stefan Lippers-Hollmann <s.l-h@gmx.de> for 
the Debian project (but may be used by others).
