.TH sshdeactivate "25" "February 2017" "sshdeactivate" "System Administration Commands (8)"
.SH NAME
sshdeactivate - deactivate sshd
.SH SYNOPSIS
.B sshdeactivate
.SH DESCRIPTION
`sshdeactivate' stops and disable the ssh daemon.
.SH "SEE ALSO"
.BR sshd
.SH AUTHOR
This manual has been written by Alf Gaida <agaida@siduction.org> for
the Debian project (but may be used by others).
