#!/bin/sh
# sshdeactivate - Stop and disable SSHD

# Copyright 2017  Alf Gaida <agaida@siduction.org>

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2 of the
# License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# rm -f /etc/ssh/ssh_host_rsa_key \
# rm -f /etc/ssh/ssh_host_rsa_key.pub
# rm -f /etc/ssh/ssh_host_dsa_key \
# rm -f /etc/ssh/ssh_host_ecdsa_key \
# rm -f /etc/ssh/ssh_host_ecdsa_key.pub
# rm -f /etc/ssh/ssh_host_ed25519_key \
# rm -f /etc/ssh/ssh_host_ed25519_key.pub

systemctl disable ssh
systemctl stop ssh

echo ""
echo -n "Finished. Press Enter to exit."
read DUMMY

exit 0
