.TH sshstart "8" "January 2015" "sshstart" "System Administration Commands (8)"
.SH NAME
sshstart - starts sshd
.SH SYNOPSIS
.B sshstart
.SH DESCRIPTION
`sshstart', generates sshd system keys, starts the ssh dæmon and asks for user
password, to allow remote access to the (live-)system.
hibernation images.
.SH "SEE ALSO"
.BR sshd
.SH AUTHOR
This manual has been written by Stefan Lippers-Hollmann <s.l-h@gmx.de> for 
the Debian project (but may be used by others).
